### ISSUE TITLE
[Enhancement] Island Apps don't show up

### ISSUE THREAD

**Issue by codinginrevolt** [DroidWorksStudio/EasyLauncher#113]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/mLauncher/issues) or [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/mLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Feature description

Apps cloned using Insular/Island don't show up in the app drawer. They can still be accessed by opening the insular app itself.
It would be cool if there was the option to create a second app drawer just for the insular/island apps.

Here is the f-droid [page](https://f-droid.org/packages/com.oasisfeng.island.fdroid/) for Insular btw.

### Additional information

since there is the option of using the insular/island app to open these apps, I have marked this as a feature request and not a bug :)

thanks for creating and maintaining this project, i've been using the launcher for a couple of days and it's so good, great for letting me "disconnect" from my phone :)

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by Gitbot-Actions** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
Ok I see I'll have a look into this for some reason only the island app itself is working for work profiles

**Comment by HeCodes2Much** [comment]
#114 same issue
