### ISSUE TITLE
[Bug Report] profile/work apps do not appear in app list

### ISSUE THREAD

**Issue by kennethrrosen** [DroidWorksStudio/EasyLauncher#114]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/mLauncher/issues) or [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Phone Make & model

Google - Pixel 6a

### App version

0.2.2

### Android version

Android 14

### How did you download the software?

F-Droid

### Bug description

Using shelter, secondary profile/work apps are not appearing in the app list.

### Steps to reproduce the bug

Use Shelter or Android's profile feature to add apps under a separate profile. 

### Expected behavior

All apps appear in apps section. Only main profile apps appear. 

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by kennethrrosen** [comment]
Amazing. Thank you. Looking forward to the release @HeCodes2Much

**Comment by HeCodes2Much** [comment]
Keep in mind when you do the update do a backup before bad to save the settings as you will need to clear cache and redo the apps too as this will break the current install.
