### ISSUE TITLE
[Bug Report] swiping is limited to areas where app names are not located

### ISSUE THREAD

**Issue by kennethrrosen** [DroidWorksStudio/EasyLauncher#116]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/mLauncher/issues) or [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Phone Make & model

Google - Pixel 6a

### App version

0.2.2

### Android version

Android 14

### How did you download the software?

F-Droid

### Bug description

If I want to swipe right to get to the search function, the swipe action (or the press and hold to get to settings) has to be done in the space not occupied by an app name. For instance, if Chrome is one of the apps, and its aligned right, any space across the screen from the app name will open the app, not preform one of the other swipe functions.  

### Steps to reproduce the bug

Use EasyLauncher as advertised

### Expected behavior

Anywhere that isn't an explicit app name should allow for gestures. 

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by Gitbot-Actions** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
I will look into a fix for this soon

**Comment by HeCodes2Much** [comment]
[#5c77a2](https://github.com/DroidWorksStudio/EasyLauncher/commit/5c77a238d5b6cf06b5607fc1c24a65ab51661f11) fixed

**Comment by kennethrrosen** [comment]
Thanks much! @HeCodes2Much
