### ISSUE TITLE
[Crash Report] F-Droid 0.2.3 build keeps crashing instantly

### ISSUE THREAD

**Issue by ddogfoodd** [DroidWorksStudio/EasyLauncher#124]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have created the title to best match the issue.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Phone Make & model

Fairphone - Fairphone 5

### App version

0.2.3

### Android version

Android 14

### How did you download the software?

F-Droid

### Crash description

After update the app crashes every time I want to go to the home screen, it keeps crashing.

### Steps to reproduce the crash

1. Update the app and go to the home screen
2. See the crash and get thrown back to the opened apps

### Expected behavior

No crash

### Additional information

I am scared because I don't know how to get out of a crash loop. I tried rebooting but was stuck in a crash loop. I don't know how to access the settings or anything and was lucky that f-droid was still open in background so I could use it to uninstall the launcher and rescue my device. Therefore I wasn't able to get the logs.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
This is due to a setting change if you reinstall it or clear cache then it will fix it. I myself also use a FairPhone 5
