### ISSUE TITLE
[Enhancement] Full Backup of Launcher Settings, Including Favorite Apps and Custom App Names

### ISSUE THREAD

**Issue by mathe00** [DroidWorksStudio/EasyLauncher#125]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/mLauncher/issues) or [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/mLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Feature description

I would like to suggest a feature enhancement for EasyLauncher that would improve the backup functionality. Specifically, the backup option should include all launcher settings to ensure a complete restoration experience. This should cover:

1. **Favorite Apps and Homepage Layout:** Currently, it appears that the backup does not include the specific list of apps marked as favorites or those placed on the homepage. Including this information in the backup would allow users to restore their preferred app layout without manually reorganizing after a reset or on a new device.
2. **Custom App Names:** Users often rename apps for easier identification or personalization. The backup should also remember these custom names assigned to apps in the launcher. This will help maintain a consistent user experience across devices or after reinstallation.

This enhancement would greatly benefit users who want a seamless transition between devices or need to restore settings after resetting their device. It would save time and effort, making the user experience smoother and more enjoyable.

### Additional information

This feature would align with EasyLauncher’s goal of providing a customizable and user-friendly experience. Having the ability to fully back up and restore all personalized settings, including app organization and custom names, would enhance user satisfaction and usability.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
This is something I am working on getting done.

**Comment by mathe00** [comment]
> This is something I am working on getting done.

Perfect ! Thanks

**Comment by HeCodes2Much** [comment]
This will be next on my list as soon as I have finished with the language selection feature.

**Comment by HeCodes2Much** [comment]
Done and ready for 0.3.2
