### ISSUE TITLE
[Bug Report] Sometimes overlays stop appearing

### ISSUE THREAD

**Issue by ddogfoodd** [DroidWorksStudio/EasyLauncher#128]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/mLauncher/issues) or [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Phone Make & model

Fairphone - Fairphone 5

### App version

0.2.3

### Android version

Android 14

### How did you download the software?

F-Droid

### Bug description

After some time overlays stop working until device reboot or launcher force stop. That is: the App drawer is invisible or doesn't appear anymore when using the gesture. However the keyboard still appears and typing a full name of an app can launch it, so it seems to be a visual bug. The launcher settings can also not accessed when this happens.

### Steps to reproduce the bug

I don't know much, unfortunately.
1. Use the launcher for some time.
2. Use gestures until the bug occurs.

### Expected behavior

The app drawer gets shown as usual, launcher settings are still accessible.

### Additional information

I can remember that this bug occured also in version 0.2.2

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
that's even more strange because that's the same phone I use myself.
