### ISSUE TITLE
[Enhancement] Custom Search Engine or use browser default

### ISSUE THREAD

**Issue by ddogfoodd** [DroidWorksStudio/EasyLauncher#131]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/EasyLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Feature description

It would be great to be able to add a custom search engine. Or maybe if that's easier the launcher could use the browsers default search engine for search, since this is often customizable.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
I will look into adding the option to use the default search from default browser as the default. but first i need to finish the new settings panel.

**Comment by HeCodes2Much** [comment]
So android doesn't allow this but I can have it open in the default search app?

**Comment by HeCodes2Much** [comment]
Fixed in the next build.
