### ISSUE TITLE
[Enhancement] Work Profile Apps on Favorites

### ISSUE THREAD

**Issue by 4r1-60ld** [DroidWorksStudio/EasyLauncher#135]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/EasyLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Feature description

Hi! It seems that I cannot add Work Profile Apps to Favorites? I couls not find any information on this so I do not know if this is a bug or a feature that does not excist. If not, it would be really good to get it included. Thank you!

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
Ya been having issues with work profiles not working right I need to work them out.

**Comment by 4r1-60ld** [comment]
> Ya been having issues with work profiles not working right I need to work them out.

Thanks for the quick reply and thank you for your work with this Launcher.

**Comment by HeCodes2Much** [comment]
this should be done for version 0.3.2
