### ISSUE TITLE
[Crash Report] Error of version number causing crashes in last F-Droid version (v0.2.4)

### ISSUE THREAD

**Issue by megaaa13** [DroidWorksStudio/EasyLauncher#138]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have created the title to best match the issue.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Phone Make & model

OnePlus - 7T (HD1903)

### App version

0.2.4

### Android version

Android 12

### How did you download the software?

F-Droid

### Crash description

The launcher crash at launch, and don't recover

### Steps to reproduce the crash

Launch the app

### Expected behavior

The launcher is supposed to start

### Logs

> APP_VERSION_CODE=24
> APP_VERSION_NAME=0.2.4
> ANDROID_VERSION=12
> PHONE_MODEL=HD1903
> CUSTOM_DATA=
> STACK_TRACE=java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: bf546b2e7c68fab20efdd561b2bf49c0, found: 0ae1c03a7dbbb3279196fd52c37edcef
> 	at androidx.recyclerview.widget.j.o(SourceFile:109)
> 	at v0.g.onOpen(SourceFile:16)
> 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
> 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
> 	at v0.g.i(SourceFile:5)
> 	at v0.g.v(SourceFile:64)
> 	at v0.g.b(SourceFile:24)
> 	at v0.h.b(SourceFile:10)
> 	at androidx.room.w.inTransaction(SourceFile:7)
> 	at androidx.room.w.assertNotSuspendingTransaction(SourceFile:1)
> 	at androidx.room.w.query(SourceFile:4)
> 	at a.a.P(SourceFile:12)
> 	at com.github.droidworksstudio.launcher.data.dao.AppInfoDAO_Impl$9.call(SourceFile:2)
> 	at com.github.droidworksstudio.launcher.data.dao.AppInfoDAO_Impl$9.call(SourceFile:1)
> 	at androidx.room.c.invokeSuspend(SourceFile:83)
> 	at Y1.a.resumeWith(SourceFile:9)
> 	at p2.C.run(SourceFile:115)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
> 	at java.lang.Thread.run(Thread.java:1012)
> 	Suppressed: u2.g: [h0{Cancelling}@a077e38, Dispatchers.Main.immediate]
> 
> LOGCAT=09-15 16:12:32.968 D/a       (16835): Loaded Collector of type org.acra.collector.DropBoxCollector
> 09-15 16:12:32.968 D/a       (16835): Loaded Collector of type org.acra.collector.LogCatCollector
> 09-15 16:12:32.968 D/a       (16835): Loaded Collector of type org.acra.collector.LogFileCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.MediaCodecListCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.MemoryInfoCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.PackageManagerCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.ReflectionCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.SettingsCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.SharedPreferencesCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.SimpleValuesCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.StacktraceCollector
> 09-15 16:12:32.969 D/a       (16835): Loaded Collector of type org.acra.collector.ThreadCollector
> 09-15 16:12:32.971 D/a       (16835): Loaded Collector of type org.acra.collector.TimeCollector
> 09-15 16:12:32.972 D/a       (16835): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.scheduler.SenderSchedulerFactory]
> 09-15 16:12:32.972 D/a       (16835): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.config.ReportingAdministrator]
> 09-15 16:12:32.980 D/a       (16835): ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.startup.StartupProcessor]
> 09-15 16:12:32.981 D/a       (16835): Loaded StartupProcessor of type org.acra.startup.UnapprovedStartupProcessor
> 09-15 16:12:34.684 E/MultiApp.Impl(16835): OplusMultiAppImpl
> 09-15 16:12:34.684 D/AppCompatDelegate(16835): Checking for metadata for AppLocalesMetadataHolderService : Service not found
> 09-15 16:12:34.695 D/a       (16835): onActivityCreated class com.github.droidworksstudio.launcher.ui.activities.MainActivity
> 09-15 16:12:34.696 I/oplus.android.OplusFrameworkFactoryImpl(16835): Unknow feature:IOplusTextViewRTLUtilForUG
> 09-15 16:12:34.706 D/CompatibilityChangeReporter(16835): Compat change id reported: 171228096; UID 10568; state: ENABLED
> 09-15 16:12:34.706 D/ScrollOptimizationHelper(16835): can't find the config file for optimizaiton
> 09-15 16:12:34.706 D/ScrollOptimizationHelper(16835): will not debug for debug is false
> 09-15 16:12:34.706 I/oplus.android.OplusFrameworkFactoryImpl(16835): get feature:IOplusDynamicVsyncFeature
> 09-15 16:12:34.706 I/oplus.android.OplusFrameworkFactoryImpl(16835): get feature:IOplusDynamicVsyncFeature
> 09-15 16:12:34.707 I/oplus.android.OplusFrameworkFactoryImpl(16835): get feature:IOplusDynamicVsyncFeature
> --------- beginning of system
> 09-15 16:12:34.708 E/OplusCustomizeRestrictionManager(16835): sInstance is null, start a new sInstance
> 09-15 16:12:34.716 I/oplus.android.OplusFrameworkFactoryImpl(16835): get feature:IOplusDynamicVsyncFeature
> 09-15 16:12:34.716 I/oplus.android.OplusFrameworkFactoryImpl(16835): get feature:IOplusDynamicVsyncFeature
> 09-15 16:12:34.716 I/oplus.android.OplusFrameworkFactoryImpl(16835): get feature:IOplusDynamicVsyncFeature
> 09-15 16:12:34.717 D/OplusInputMethodUtil(16835): init DEBUG to false, update DEBUG_IME to false
> 09-15 16:12:34.717 D/OplusInputMethodUtil(16835): init DEBUG to false, update DEBUG_IME to false
> 09-15 16:12:34.723 D/CompatibilityChangeReporter(16835): Compat change id reported: 170233598; UID 10568; state: DISABLED
> 09-15 16:12:34.724 D/preferenceHelper(16835): {AUTOMATIC_OPEN_APP=false, HOME_TIME_ALIGNMENT=17, WIDGET_BATTERY=2, HOME_DATE_ALIGNMENT=17, SHOW_DATE=true, TOGGLE_SETTING_LOCK=false, AUTOMATIC_KEYBOARD=false, APP_TEXT_SIZE=24.0, BATTERY_TEXT_SIZE=16.0, SHOW_BATTERY=true, TIME_TEXT_SIZE=48.0, HOME_APP_ALIGNMENT=8388611, SHOW_BATTERY_WIDGET=false, SHOW_STATUS_BAR=true, DATE_TEXT_SIZE=32.0, SWIPE_UP_ACTION=ShowRecents, SHOW_TIME=true, SHOW_APP_ICON=false, APP_TEXT_PADDING=10.0, SWIPE_DOWN_ACTION=ShowNotification, SEARCH_ENGINE=DuckDuckGo, SHOW_DAILY_WORD=false, SWIPE_LEFT_ACTION=ShowFavoriteList, SWIPE_RIGHT_ACTION=ShowAppList, DOUBLE_TAP_ACTION=LockScreen, FIRST_LAUNCH=false, LOCATION_DENIED=false}
> 09-15 16:12:34.736 I/Quality (16835): ActivityThread: activityStart delay 65 app.easy.launcher 16835
> 09-15 16:12:34.736 D/a       (16835): onActivityStarted class com.github.droidworksstudio.launcher.ui.activities.MainActivity
> 09-15 16:12:34.738 D/a       (16835): onActivityResumed class com.github.droidworksstudio.launcher.ui.activities.MainActivity
> 09-15 16:12:34.747 D/OplusSlideAnimOptHelper(16835): app.easy.launcher scrollEffectOpt enable = false
> 09-15 16:12:34.750 D/WindowManager(16835): Add to mViews: DecorView@1d420b5[MainActivity],pkg= app.easy.launcher
> 09-15 16:12:34.752 D/ExtensionsLoader(16835): createInstance(64bit) : createExtendedFactory
> 09-15 16:12:34.753 D/ExtensionsLoader(16835): Opened libhwuiextimpl.so
> 09-15 16:12:34.753 D/ExtensionsLoader(16835): createInstance(64bit) : createExtendedFactory
> 09-15 16:12:34.754 D/ExtensionsLoader(16835): Opened libSchedAssistExtImpl.so
> 09-15 16:12:34.754 E/p.easy.launche(16835): ofbOpen failed with error=No such file or directory
> 09-15 16:12:34.754 E/p.easy.launche(16835): sysOpen failed with error=No such file or directory
> 09-15 16:12:34.765 D/Tag     (16835): ShowTime Home: true
> 09-15 16:12:34.765 D/Tag     (16835): ShowTime Home: true
> 09-15 16:12:34.774 D/nativeloader(16835): Load libSchedAssistJni.so using system ns (caller=/system/framework/oplus-framework.jar): ok
> 09-15 16:12:34.774 D/ExtensionsLoader(16835): createInstance(64bit) : createExtendedFactory
> 09-15 16:12:34.774 D/ExtensionsLoader(16835): Opened libSchedAssistExtImpl.so
> 09-15 16:12:34.796 D/ExtensionsLoader(16835): createInstance(64bit) : createExtendedFactory
> 09-15 16:12:34.797 D/ExtensionsLoader(16835): Opened libSchedAssistExtImpl.so
> 09-15 16:12:34.798 V/OplusZoomWindowDecorViewHelper(16835): setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.30679221
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): QUALCOMM build                   : 2f950bf, I802c3b73eb
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): Build Date                       : 06/14/21
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): OpenGL ES Shader Compiler Version: EV031.32.02.12
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): Local Branch                     : mybranchebcd58da-bf05-f13c-94fa-5cb90179c3d8
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): Remote Branch                    : NONE
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): Reconstruct Branch               : NOTHING
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): Build Config                     : S P 10.0.7 AArch64
> 09-15 16:12:34.798 I/AdrenoGLES-0(16835): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
> 09-15 16:12:34.801 I/AdrenoGLES-0(16835): PFP: 0x016ee190, ME: 0x00000000
> 09-15 16:12:34.811 D/hw-ProcessState(16835): Binder ioctl to enable oneway spam detection failed: Invalid argument
> 09-15 16:12:34.834 I/Quality (16835): Skipped: false 2 cost 46.287888 refreshRate 0 processName app.easy.launcher
> 09-15 16:12:34.840 D/SurfaceComposerClient(16835): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
> 09-15 16:12:35.252 E/a       (16835): ACRA caught a IllegalStateException for app.easy.launcher
> 09-15 16:12:35.252 E/a       (16835): java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: bf546b2e7c68fab20efdd561b2bf49c0, found: 0ae1c03a7dbbb3279196fd52c37edcef
> 09-15 16:12:35.252 E/a       (16835): 	at androidx.recyclerview.widget.j.o(SourceFile:109)
> 09-15 16:12:35.252 E/a       (16835): 	at v0.g.onOpen(SourceFile:16)
> 09-15 16:12:35.252 E/a       (16835): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
> 09-15 16:12:35.252 E/a       (16835): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
> 09-15 16:12:35.252 E/a       (16835): 	at v0.g.i(SourceFile:5)
> 09-15 16:12:35.252 E/a       (16835): 	at v0.g.v(SourceFile:64)
> 09-15 16:12:35.252 E/a       (16835): 	at v0.g.b(SourceFile:24)
> 09-15 16:12:35.252 E/a       (16835): 	at v0.h.b(SourceFile:10)
> 09-15 16:12:35.252 E/a       (16835): 	at androidx.room.w.inTransaction(SourceFile:7)
> 09-15 16:12:35.252 E/a       (16835): 	at androidx.room.w.assertNotSuspendingTransaction(SourceFile:1)
> 09-15 16:12:35.252 E/a       (16835): 	at androidx.room.w.query(SourceFile:4)
> 09-15 16:12:35.252 E/a       (16835): 	at a.a.P(SourceFile:12)
> 09-15 16:12:35.252 E/a       (16835): 	at com.github.droidworksstudio.launcher.data.dao.AppInfoDAO_Impl$9.call(SourceFile:2)
> 09-15 16:12:35.252 E/a       (16835): 	at com.github.droidworksstudio.launcher.data.dao.AppInfoDAO_Impl$9.call(SourceFile:1)
> 09-15 16:12:35.252 E/a       (16835): 	at androidx.room.c.invokeSuspend(SourceFile:83)
> 09-15 16:12:35.252 E/a       (16835): 	at Y1.a.resumeWith(SourceFile:9)
> 09-15 16:12:35.252 E/a       (16835): 	at p2.C.run(SourceFile:115)
> 09-15 16:12:35.252 E/a       (16835): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 09-15 16:12:35.252 E/a       (16835): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
> 09-15 16:12:35.252 E/a       (16835): 	at java.lang.Thread.run(Thread.java:1012)
> 09-15 16:12:35.252 E/a       (16835): 	Suppressed: u2.g: [h0{Cancelling}@a077e38, Dispatchers.Main.immediate]
> 09-15 16:12:35.252 D/a       (16835): Building report
> 09-15 16:12:35.252 D/a       (16835): Starting collectors with priority FIRST
> 09-15 16:12:35.252 D/a       (16835): Calling collector org.acra.collector.DropBoxCollector
> 09-15 16:12:35.252 D/a       (16835): Calling collector org.acra.collector.LogCatCollector
> 09-15 16:12:35.252 D/a       (16835): Collector org.acra.collector.DropBoxCollector completed
> 09-15 16:12:35.252 D/a       (16835): Calling collector org.acra.collector.StacktraceCollector
> 09-15 16:12:35.252 D/a       (16835): Collector org.acra.collector.StacktraceCollector completed
> 09-15 16:12:35.253 D/a       (16835): Retrieving logcat output (buffer:default)...
> 
> IS_SILENT=false
> REPORT_ID=3cf7ed12-8c39-4c45-8658-9f4f65a13e15
> USER_CRASH_DATE=2024-09-15T16:12:35.283+02:00
> USER_COMMENT=
> USER_EMAIL=

### Additional information

This will probably be resolved in the v0.2.5, but it seems to not be mentionned so...

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
This is nothing Todo with room itself if you updated from 0.2.3 to 0.2.4 a setting has changed type and if that settings is already set as an INT when it is no longer an INT then it will crash.
