### ISSUE TITLE
[Enhancement] Improve App Search

### ISSUE THREAD

**Issue by JustStayingPositive** [DroidWorksStudio/EasyLauncher#150]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/EasyLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Feature description

Add the option to have app searching list by 'exact match' first instead of list order.

As an example:
Say you have the apps `Life360`, `Spotify`, and `iFunny` installed. Currently, beginning a search by typing in `if` will bring the apps up in alphabetical order:
```
Life360
Spotify
iFunny
```
Using the same search of `if` would instead bring the results up as follows with this change:
```
iFunny
Life360
Spotify
```
Prioritizing `iFunny` because it matches the search exactly, then showing other apps that also contain `if` somewhere in their name. My reasoning is that if the user intends to search for the other two apps, they would begin their search with either `li` or `sp` respectively instead of `if`, and thus do not need them as the first results in the list.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
Done in 0.2.7 / Nightly
