### ISSUE TITLE
[Bug Report] Apps not properly sorting

### ISSUE THREAD

**Issue by JustStayingPositive** [DroidWorksStudio/EasyLauncher#153]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Phone Make & model

Samsung Galaxy S24 Ultra

### App version

0.2.6

### Android version

Android 14

### How did you download the software?

Github (Release)

### Bug description

A handful of apps are at the bottom of the list instead of their correct alphabetical position

### Steps to reproduce the bug

Unsure of exact steps, but occasionally long pressing on apps, hiding apps, or installing apps causes the list to bug out a little.

### Expected behavior

Apps to he sorted to their proper alphabetical order

### Screenshots/Screen recordings

![Screenshot_20241028_145447_Easy Launcher](https://github.com/user-attachments/assets/2715286f-5f29-417d-8992-435fbabef1ba)

### Additional information

Restarting the launcher does fix the bug.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
you can rename them with caps to fix this.
