### ISSUE TITLE
[Enhancement] Personalization Improvements

### ISSUE THREAD

**Issue by DracheWhitecape** [DroidWorksStudio/EasyLauncher#154]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/EasyLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Feature description

The app itself is next to perfect, but i think it could have some use to have options to customize screen switching animations.

i think it would be better If If you had the option to customize in swipe and tap commands, the option to open the application customization menu instead of just pressing.

Also, it would be nice if fixed the fact the last Module of the section "Look and Feel", the option to change the font, is Inaccessible to those who have the navigation bar is active.

For last (and maybe least), i think it would be cool if the option to change launchers were more Intuitively on display on the setting menu than in "advanced", but this is more an prefference of mine.

### Additional information

Congrarilations on this app, its absolutely brilliant.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
If you can can you please go though the thing you requested and let me know which ones ii haven't done cecause it looks to me that most of this already is..

**Comment by DracheWhitecape** [comment]
Hmmm I downloaded the update but it seems that the same things continue.
 1) The animations for changing screens continue to be unchangeable or unreremovable.
 2) The option to change the font is still inaccessible/in conflict with the Android bottom bar
3) still cant have the swipe command to, for example, open the settings of the Launcher, Replacing the need to keep pressing the screen for this.

![Screenshot_20241125_144047_Easy Launcher](https://github.com/user-attachments/assets/19b2be79-6c9f-49b4-8e24-c0f8ff52496d)

(Example image of navigation bar conflict with change fonts option)

But thanks to read the feeback.

**Comment by HeCodes2Much** [comment]
Number 1 I won't be adding and number 3 I will look into as I like that idea to allow swipe gestures to also be configured to open settings.

Number 2 you should be able to scroll the settings to be able to get to that settings.
