### ISSUE TITLE
[Bug Report] clearing recent apps list doesnt return home

### ISSUE THREAD

**Issue by bbenne10** [DroidWorksStudio/EasyLauncher#156]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Phone Make & model

Google Pixel 6a

### App version

0.2.6

### Android version

CalyxOS 5.12.0 (Android 14)

### How did you download the software?

F-Droid

### Bug description

After clearing all recent applications from the application switcher, the launcher stays at the empty switcher screen.

### Steps to reproduce the bug

1) Launch one or more applications.
2) Using the application switcher, close all of the open applications.

### Expected behavior

Every launcher I am aware of goes back to the main home screen in this scenario.

### Screenshots/Screen recordings
![Open application](https://github.com/user-attachments/assets/c810504a-0755-48ee-882f-d3c7608eb3cd)
![After closing the above window](https://github.com/user-attachments/assets/f1eff687-9e52-4d8e-8d45-a72656f49904)

### Additional information

I believe that there is some other "planing" issue with the window the homescreen itself draws to. I cannot say whether this is a related issue or not. 

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

### Donation Name

n/a

**Comment by HeCodes2Much** [comment]
this doesnt seem to be an issue on any testing i have tried does it happen every time for you?

**Comment by bbenne10** [comment]
It *was* consistent. Im unsurewhat has changed lately, but it is no longer triggering. The "planing" issues were semi-consistent, but I did not havea MVP reproduction but are now not showibgup either? 

Stillon 0.2.6, so no change there...

**Comment by HeCodes2Much** [comment]
Can't reproduce.
