### ISSUE TITLE
[Bug Report] Search does not open correct app

### ISSUE THREAD

**Issue by JustStayingPositive** [DroidWorksStudio/EasyLauncher#161]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Phone Make & model

Samsung Galaxy S24 Ultra

### App version

0.2.7

### Android version

Android 14

### How did you download the software?

F-Droid

### Bug description

No matter what I type into the search, pressing enter results in the first listed app being opened (in my case, AdBlock for Samsung internet, which is hidden but still opened)

### Steps to reproduce the bug

Open apps list, type anything into the search bar (valid or not), press enter the alphabetically first app (hidden or not) will open

### Expected behavior

Open apps list, beginning typing app name, press enter when correct result is shown, correct app opened

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/4f5b0df2-65a3-4c67-97c3-c656a7966925

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
I'll fix this.... Also you did not install it with fDroid as fDroid does not have that build yet.

**Comment by HeCodes2Much** [comment]
Fixed in the latest commits
