### ISSUE TITLE
[Enhancement] Language selector

### ISSUE THREAD

**Issue by Sarsharses** [DroidWorksStudio/EasyLauncher#162]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/EasyLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Feature description

Hiya, great work so far!
Would like to suggest adding a dropdown or some sort of other selection menu for switching the displayed language of the launcher settings.

I, for example, don't necessarily like to use Dutch for my primary interface when I unlock my phone, but I need several other apps that don't offer on the fly switching in my native language. Other people might possibly enjoy the same functionality.

This in turn would make it a lot easier to contribute to translations without having to change device language everytime to scout where the next string is located.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

### Donation Name

sarsharses

**Comment by HeCodes2Much** [comment]
I'm not gonna do this right away as its not that important if the only translation that works well is English but as soon as 2 or more extra languages have 50% or more worked on this i will look into adding it.

**Comment by Sarsharses** [comment]
That's fair. Can imagine there's boatloads of more important stuff, just wanted to put this out there. I'll see to it that the Dutch translation will be up to date.

**Comment by HeCodes2Much** [comment]
ya if `Shiinrow` had the dutch language at at least 75% then i could see the point in adding it but i will only add languages as they reach the 75% mark.  its not too had to do this as i did it for mLauncher before so i can just use the same code but make it work for the style of EasyLauncher.

**Comment by Sarsharses** [comment]
Hence why I figured it might be a nice addition seeing you already implemented it once ;)  Makes absolute sense to not add anything that isn't being actively updated.

**Comment by Sarsharses** [comment]
Dutch should be fairly sanitized now on Crowdin.
I'll keep an eye out for missing or strange translations.

**Comment by HeCodes2Much** [comment]
> Dutch should be fairly sanitized now on Crowdin. I'll keep an eye out for missing or strange translations.

i have added you as a proofreader if you want to go on and accept them so i can do a PR and add them then i will go about and add this feature.

**Comment by HeCodes2Much** [comment]
#165 is ready for when you are done

**Comment by HeCodes2Much** [comment]
@Sarsharses almost done.

**Comment by Sarsharses** [comment]
Dutch is 100%-ed now :)

**Comment by HeCodes2Much** [comment]
> Dutch is 100%-ed now :)

Thanks

this isn's the spot to ask this but do other options like the select app for gestures work in non english?

**Comment by Sarsharses** [comment]
I'll get back to you when I finish work and can properly do some tests.

**Comment by HeCodes2Much** [comment]
![New Project](https://github.com/user-attachments/assets/c582aeb3-1a27-44d7-8c07-aa8bc6ecee55)

All done and ready to push :)

**Comment by Sarsharses** [comment]
Looks great! 

Only found one thing that doesn't work for me now and that is that the 'Easy Launcher Actions Service' needed for screen locking, power dialog and recent app showing can not be enabled but this might be something in my device settings.

**Comment by Sarsharses** [comment]
Right, might be good to try that then.

Ran into a bug just now though where the gestures seen to crash whenever one of them has been performed. Was there any specific reason you asked about the open app one? 

The nightly build doesn't seem to have this issue. If you want I can try to find out how to reproduce this tomorrow.

**Comment by Sarsharses** [comment]
Alright, it occurs within the nightly as well. Whenever the applist is aligned to the any side the area to the other side bugs out the gestures. Only place where they register correctly is in the empty space below the applist. 

Added screenshot for clarification. If you need this in a seperate bugreport let me know
![Screenshot_2024-11-25-22-54-27-55_1d151929efb2ddc7073e99a7f966a46b](https://github.com/user-attachments/assets/9c167404-5fa3-4006-b838-5874018d984e)

**Comment by HeCodes2Much** [comment]
> Alright, it occurs within the nightly as well. Whenever the applist is aligned to the any side the area to the other side bugs out the gestures. Only place where they register correctly is in the empty space below the applist. 
> 
> Added screenshot for clarification. If you need this in a seperate bugreport let me know
> ![Screenshot_2024-11-25-22-54-27-55_1d151929efb2ddc7073e99a7f966a46b](https://github.com/user-attachments/assets/9c167404-5fa3-4006-b838-5874018d984e)
> 

Did this only start to happen since 0.2.7 and after if so then I know why and I'll fix it asap

**Comment by HeCodes2Much** [comment]
> The nightly build doesn't seem to have this issue. If you want I can try to find out how to reproduce this tomorrow.

Maybe a fresh install is what fixed it as the nightly should be the same. I didn't seem to have any crashes.

**Comment by Sarsharses** [comment]
No clue, only noticed you were working on this because I saw you set the mLauncher repo to read only and this was already at 0.2.7 so would have to backtrack as well.

**Comment by Sarsharses** [comment]
> Maybe a fresh install is what fixed it as the nightly should be the same. I didn't seem to have any crashes.
> 

Ah my bad I forgot to mention I just checked the nightly and it has the same issue.

> If you can email the crash report with the data filled out I can read the logs and find out why.
>
It softcrashes so there is no log I suppose?

**Comment by HeCodes2Much** [comment]
I will have a look tomorrow at some of these issues as I think I know how to fix them pretty quickly.

**Comment by HeCodes2Much** [comment]
@Sarsharses [#05133510](https://github.com/DroidWorksStudio/EasyLauncher/commit/051335107deb4f8db599ab74847d3d27b1f7e8ea) has fixed the issue within that screenshot

**Comment by HeCodes2Much** [comment]
> @Sarsharses [#05133510](https://github.com/DroidWorksStudio/EasyLauncher/commit/051335107deb4f8db599ab74847d3d27b1f7e8ea) has fixed the issue within that screenshot

This doesn't seem to have fixed the issue so I'll need to take a deeper look into it more and see why that stopped working right after I did the commit and did a release.

**Comment by Sarsharses** [comment]
G'morning, the language selector looks pretty neat, however it doesn't actually change the language when the settings are updated. Tried to see if maybe it'd work if my systemlanguage was set to English but that didn't help.

**Comment by HeCodes2Much** [comment]
It did work but I guess playing about with other stuff broke it along with gestures I'll look at a fix soon
