### ISSUE TITLE
[Bug Report] Alignment breaks when not using English

### ISSUE THREAD

**Issue by Sarsharses** [DroidWorksStudio/EasyLauncher#167]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Phone Make & model

Oppo Find X5 Pro

### App version

0.2.7

### Android version

14

### How did you download the software?

Github (Release)

### Bug description

When trying to change the alignment of on-screen elements while using a different language than English (Dutch in this case) the settings default back to LEFT instead of their corresponding option.

### Steps to reproduce the bug

1. Align certain elements while using English to the center or right.
2. Change device language to a different language. (Dutch is certain to break)
3. Go to Launcher settings > Kijk en voel (Look and Feel) > Uitlijning (Alignment)
4. Try to change the alignment of certain elements.
5. This is where it breaks.

### Expected behavior

One would expect changing these settings to behave properly.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
I'll have a look into this. I think it may be the switch statement I'll take a look after work.

**Comment by HeCodes2Much** [comment]
@Sarsharses I have found the issue. The Left Center and Right are hard coded as them spelling so I need to change it to a 0,1 or 2 instead of using text as the selection.

**Comment by Sarsharses** [comment]
Figured it'd be something like that, thanks for looking into it
