### ISSUE TITLE
[Bug Report] Date/time/battery are briefly displayed when opening an app from the app drawer

### ISSUE THREAD

**Issue by xfzv** [DroidWorksStudio/EasyLauncher#175]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Phone Make & model

OnePlus 7 Pro

### App version

0.2.8

### Android version

15

### How did you download the software?

Github (Release)

### Bug description

When opening any app from the app drawer, date/time (in top left corner) and battery (in top right corner) are briefly displayed before the app is fully displayed.
"Show Date" / "Show Time" and "Show Battery" are all disabled in "Look And Feel" section, not sure why they briefly show up when opening an app.

### Steps to reproduce the bug

1. Disable "Show Date" / "Show Time" and "Show Battery" in "Look And Feel"
2. Open the app drawer
3. Tap any app
4. Date/time (in top left corner) and battery level (in top right corner) are briefly displayed before the app is fully displayed

### Expected behavior

Date/time and battery aren't briefly displayed when opening an app from the app drawer.

### Additional information

Increasing window animation / transition animation / animator duration scales in Android developer settings from 1.0x to 2.0x doesn't affect how long the date/time/battery are displayed so I don't think this has anything to do with system animations. 

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
Can you share a recording as I can't seem to do the same.

**Comment by HeCodes2Much** [comment]
Can't really do much about this if I can't see it in action. Can you maybe find steps that make it 100% replicated so I can look more into it and see if I can make it do the same so for now I'm closing this.
