### ISSUE TITLE
[Enhancement] add home button option

### ISSUE THREAD

**Issue by GurrenLagann114** [DroidWorksStudio/EasyLauncher#176]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/EasyLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Feature description

It would be best to have a dedicated "home button" to show recent apps rather than the default swipe up gesture, which is (a lot) more intuitive for the app drawer,

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
So like I have for the search button on the app list but have one that can be toggled in the setting on the home screen?

**Comment by GurrenLagann114** [comment]
Yeah, so instead of swiping up as default you press (or swipe if you have gestures) the home button instead.

**Comment by HeCodes2Much** [comment]
I'm not really interested in adding any buttons to the home screen as gestures work and android has its own 3 button menu system that can do this sorry buddy.

**Comment by GurrenLagann114** [comment]
You misunderstood. 

I didn't say to add any button on the homescreen, just add an action that does something by pressing the home button (as in the default one of android), kinda like Lawnchair.

**Comment by HeCodes2Much** [comment]
That would interfere with the tap, hold and double tap actions so it would have had to be a button like Niagara Launcher has.
