### ISSUE TITLE
[Enhancement] Set custom calendar app

### ISSUE THREAD

**Issue by JustStayingPositive** [DroidWorksStudio/EasyLauncher#181]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/EasyLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Feature description

When tapping the date on the home screen, open the app set by the user through settings (similar to default search engine selection)

### Additional information

Could also be done for the clock I suppose? But not many variations of clock apps exist/are regularly switched to over the system default (I'm assuming). Calendar apps might be switched more often. I just moved away from Google (almost) entirely, including for my calendar, so being able to set my new calendar app would be nice

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
Ya this may be a good idea I'm not too sure how I wanna go about doing it though but I'll try out a few different ways I may just do it the same way as gestures.

**Comment by HeCodes2Much** [comment]
Now working on this I am going to create a dialogue for both alarm apps and calendar apps so both date and time can use a selected app from them lists.

I hope to have it ready for next release.

**Comment by HeCodes2Much** [comment]
Sorry but I don't need to do anything with this as that is already the default action if you have more then 1 calendar installed.

**Comment by HeCodes2Much** [comment]
![Screenshot_20241205-072220.png](https://github.com/user-attachments/assets/c1ea7580-5e5e-404a-a428-c9ca8b82f9bb)



Ya some odd reason proton doesn't show in the list I will contact them about it.
