### ISSUE TITLE
[Bug Report] Search is broken since 0.2.7

### ISSUE THREAD

**Issue by sunng87** [DroidWorksStudio/EasyLauncher#183]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Phone Make & model

Motorola x30pro

### App version

0.2.8

### Android version

14

### How did you download the software?

F-Droid

### Bug description

Since 0.2.7 the search behavior changes a lot. One of my key use case is I have a lot of non-English named apps, like 哔哩哔哩. To be able to search them, I manually appended a english name, like `哔哩哔哩 bilibili`. So when I searched `bil` it should open the app. 

However, this behavior changed in 0.2.7 and it no longer shows anything with `bil`.

My filter strength was set to 25.

### Steps to reproduce the bug

rename an app to `哔哩哔哩bilibili`
search `bil`

### Expected behavior

opens the app

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
This is not a big this is a feature turn filter down to 0 and it should work as it was.
