### ISSUE TITLE
[Bug Report] 0.3.0 update broke gestures

### ISSUE THREAD

**Issue by Sarsharses** [DroidWorksStudio/EasyLauncher#191]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Phone Make & model

Oppo Find X5 Pro

### App version

0.3.0

### Android version

Android 14

### How did you download the software?

Github (Release)

### Bug description

The update to 0.3.0 killed some of the gestures. Up and down never register, right and left sometimes do, double tap and longpress seem to work correctly.

Tried if changing my language would solve anything but it didn't, neither did aligning home to the bottom of the screen or adjusting the swipe treshold.

### Steps to reproduce the bug

1. Open launcher
2. Swipe up or down
3. ???
4. Profit

### Expected behavior

Gestures to register

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
Ya we have been doing testing in telegram so I know about this issue and a few others.

**Comment by HeCodes2Much** [comment]
This will be fixed in 0.3.1

**Comment by Sarsharses** [comment]
Wonderful! Will look out for it :)

**Comment by Sarsharses** [comment]
Nightly works like a charm 👌🏼
