### ISSUE TITLE
[Enhancement] Some mLauncher Features missing

### ISSUE THREAD

**Issue by Maxitendo1** [DroidWorksStudio/EasyLauncher#216]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/EasyLauncher/issues) or [closed](https://github.com/DroidWorksStudio/EasyLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/DroidWorksStudio/EasyLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/EasyLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [ ] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the EasyLauncher mission.

### Feature description

I'm missing some features for EasyLauncher as mLauncher unfortunately got archived and is not supported anymore. For example:

- [ ] - Darkening the wallpaper
- [ ] - Clicking or scrolling on apps besides their names instead of always on their names
- [ ] - Search not opening automatically if opening app drawer
- [ ] - Settings not automatically closing after leaving the launcher

I hope that we can see all of the features from mLauncher to Easy Launcher.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by CreativeCodeCat** [comment]
Not even going to entertain clone features.
