### ISSUE TITLE
[Bug Report] F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [DroidWorksStudio/EasyLauncher#34]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### App version

0.0.8

### Android version

10

### How did you download the software?

F-Droid

### Bug description

https://gitlab.com/fdroid/fdroiddata/-/jobs/6941051596

### Steps to reproduce the bug

gradle assembleRelease

### Expected behavior

It builds.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by github-tty** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
Cheers for the report ill fix that asap.

**Comment by HeCodes2Much** [comment]
@linsui sent fix as a PR
