### ISSUE TITLE
[Enhancement] Separate work profile apps from regular apps

### ISSUE THREAD

**Issue by Akselmo** [DroidWorksStudio/EasyLauncher#42]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Feature description

Like in mLauncher, i would like the work profile apps to be separate from regular apps, since now i have two firefox apps and i dont know which is which. :D 

It can be an icon or separate list, either is fine by me.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by github-tty** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
Done for next Release [untagged](https://github.com/DroidWorksStudio/EasyLauncher/releases/tag/untagged-b16c9faa3f49f1b3a556)

**Comment by Akselmo** [comment]
Thanks!
