### ISSUE TITLE
[Enhancement] widget: Accessibility Batch Force Stop User background activities App

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [DroidWorksStudio/EasyLauncher#47]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Force stop user app
completely stop all background activities of other apps.
Force stopping apps that the user is running is very useful, maybe a whitelist is needed to avoid stopping apps.
Force stop waking and background apps. Reduce consumption.

### Additional information

![Screenshot_20240530-202947](https://github.com/DroidWorksStudio/EasyLauncher/assets/169121286/d62a0b02-aad7-4400-8953-00cf27ad5b81)

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by github-tty** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
Best to use something like the options below as I don't plan to add that to the launcher.

1. [Greenify](https://play.google.com/store/apps/details?id=com.oasisfeng.greenify): 
Greenify helps you identify and put misbehaving apps into hibernation when you are not using them.

2. [Brevent](https://play.google.com/store/apps/details?id=me.piebridge.brevent):
Brevent can help you manage app processes, preventing apps from running in the background unnecessarily.

**Comment by Zig-Rust-Odin** [comment]
> Best to use something like the options below as I don't plan to add that to the launcher.
> 
> 1. [Greenify](https://play.google.com/store/apps/details?id=com.oasisfeng.greenify):
>    Greenify helps you identify and put misbehaving apps into hibernation when you are not using them.
> 2. [Brevent](https://play.google.com/store/apps/details?id=me.piebridge.brevent):
>    Brevent can help you manage app processes, preventing apps from running in the background unnecessarily.

For both applications they require adb and root which poses a security risk to the [GrapheneOS](https://grapheneos.org/) system.
