### ISSUE TITLE
[Enhancement] Add Tasks

### ISSUE THREAD

**Issue by OnyxJet** [DroidWorksStudio/EasyLauncher#70]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Feature description

Add a feature that allows us to put simple tasks on our home screen. 

With of course the abilities to:
• Add tasks
• Edit existing tasks
• Mark as completed
• Delete tasks

### Additional information

Examples:

![IMG_20240616_093932](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/fae76837-87c7-4fa7-9317-6853e97d2016)

![IMG_20240616_094406](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/0186667c-a396-4c0b-88a1-2a2fe78cb9c2)

These are just concept examples to give you an idea of what is being asked for.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by github-tty** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.
