### ISSUE TITLE
[Enhancement] Swipe Up to Access App Drawer

### ISSUE THREAD

**Issue by OnyxJet** [DroidWorksStudio/EasyLauncher#71]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Feature description

This feature request is simple. 

**Add the option to swipe up to access the app drawer instead of swiping from right to left.**

Some people find this gesture to be more natural than swiping from right to left to open the drawer, including me.

This would be optional that way you could switch between the gesture I am suggesting vs the current right to left gesture.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by github-tty** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
You do know inside the settings there are 5 gesture you can set to a list of different things and the app list can be set as all 5 types with them being up down left and right swipe as well as double tap? So this request is already in the app.

**Comment by github-tty** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by OnyxJet** [comment]
> You do know inside the settings there are 5 gesture you can set to a list of different things and the app list can be set as all 5 types with them being up down left and right swipe as well as double tap? So this request is already in the app.

No, I do not see five gesture options anywhere. Only three very specific options. 
![Screenshot_2024-06-16-10-02-51-05_1d151929efb2ddc7073e99a7f966a46b](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/01e838f2-bdb3-4b52-bfc8-9693c0edc3b3)

**Comment by HeCodes2Much** [comment]
Ok seems like you are running on an out dated version of the app what version is this?

**Comment by OnyxJet** [comment]
> Ok seems like you are running on an out dated version of the app what version is this?

0.1.1 Downloaded from Fdroid

**Comment by HeCodes2Much** [comment]
> > Ok seems like you are running on an out dated version of the app what version is this?
> 
> 0.1.1 Downloaded from Fdroid

yes you are 3 versions behind please update as F-Droid has 0.1.4 as its latest build.
