### ISSUE TITLE
[Bug Report] UI Bug

### ISSUE THREAD

**Issue by OnyxJet** [DroidWorksStudio/EasyLauncher#73]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### App version

Version 0.1.1

### Android version

Android 13

### How did you download the software?

F-Droid

### Bug description

There is a UI text error in the settings under the gestures section. The word "notification" is cut off on the bottom.

### Steps to reproduce the bug

1. Go to settings
2. Scroll to gestures

### Expected behavior

It was expected that the settings would not have any sort of UI bug.

### Screenshots/Screen recordings

![IMG_20240616_095918](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/08673460-8964-463c-b739-38da2dbb70f6)

### Additional information

I also recommend spelling "notification" as "notifications" in this particular case.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by github-tty** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
like stated in your other issue you are using an out of date version we are on 0.1.4 on fdroid where you are still using 0.1.1

**Comment by OnyxJet** [comment]
> like stated in your other issue you are using an out of date version we are on 0.1.4 on fdroid where you are still using 0.1.1

I have just checke, and you are correct. It seems f-droid downloaded v-0.1.1 

Why this happened, I wouldn't know, perhaps you dont have the most recent version under the f-droid repository?

**Comment by OnyxJet** [comment]
> like stated in your other issue you are using an out of date version we are on 0.1.4 on fdroid where you are still using 0.1.1

How odd.

![Screenshot_2024-06-16-10-17-02-84_66a3b1c2c181ff92b8bf945e748b6fb7](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/d34d1d83-d75c-48eb-838e-57967f923c58)

![Screenshot_2024-06-16-10-16-55-62_66a3b1c2c181ff92b8bf945e748b6fb7](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/db093c10-4363-4f85-bcd6-ff0afd6b43a9)

**Comment by OnyxJet** [comment]
I will download the latest from github. Odd that fdroid does not have the latest version on my end.

**Comment by HeCodes2Much** [comment]
> perhaps you dont have the most recent version under the f-droid repository?

also going to the website only shows 0.1.2 and 0.1.3 as missing as they skip builds if a new release is within there 4 day update window but 0.1.4 is on there.

![image](https://github.com/DroidWorksStudio/EasyLauncher/assets/9284733/42b920f4-a864-4207-b7c3-c15948b890ef)

**Comment by HeCodes2Much** [comment]
> I will download the latest from github. Odd that fdroid does not have the latest version on my end.

https://f-droid.org/repo/app.easy.launcher_14.apk if you want it from fdroid

**Comment by OnyxJet** [comment]
I just updated it via github. Thanks for the notice.

**Comment by HeCodes2Much** [comment]
> I just updated it via github. Thanks for the notice.

you are welcome. you can use obtanium if you want the fastest updates. you can get obtanium on fdroid :)
