### ISSUE TITLE
[Enhancement] More Allignment Options

### ISSUE THREAD

**Issue by OnyxJet** [DroidWorksStudio/EasyLauncher#75]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/wiki) pages and made sure that the feature isn't already exist.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### Feature description

Add the option to align apps not just left, right, and center, but also the bottom as well. You could have bottom left, bottom middle, and bottom right. 

This would be similar to mlauncher.

### Additional information

Proposed locations.

![IMG_20240616_231616](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/350299af-d71a-4e2a-8d22-e1fdd3f4520c)
![IMG_20240616_231556](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/434badc3-efa1-4d0b-9db0-00989dd805fd)
![IMG_20240616_231458](https://github.com/DroidWorksStudio/EasyLauncher/assets/164056953/c6358645-4673-4188-b6db-a2fb4e5cbf4a)

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by github-tty** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
I will add this as it can be useful but Im not adding everything mLauncher has into EasyLauncher as I wanna keep them unique too.

**Comment by HeCodes2Much** [comment]
@OnyxJet as you have been spamming issues then removing the content from them I am no longer taking requests from you and have blocked you from further interactions from any of my projects.
