### ISSUE TITLE
[Bug Report] App navigation, Settings and Gesture bugs

### ISSUE THREAD

**Issue by suotux** [DroidWorksStudio/EasyLauncher#8]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues) or [closed](https://github.com/HeCodes2MuchDroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### App version

0.0.1

### Android version

Android 13

### How did you download the software?

Github (Release)

### Bug description

1. BUG 1 : Extra step to get the options on Long pressing the App name in app list and home, in both Tablet and Mobile devices.
2. BUG 2 : Search swipe up gesture, does not hide the keyboard on clicking on Home button. Pressing back button, hides the keybord.
3. BUG 3 : While using the search feature in app list, cannot go to home by pressing the Home button. (it only hides the keyboard)
4. BUG 4 : While using the search in app list, swiping left to go to home, does not hide the keyboard. Pressing on home button does not help, pressing back button hides the keyboard.

### Steps to reproduce the bug

1. Horizontal screen orientation -> Long press on App name in home/app list ->  Only shows App name and "Save" -> Swipe up holding the option menu to get/see all the options.
2. Turn On swipe up to search -> Swipe up on Home screen -> Press on Home button (It does not respond, only pressing on back button hide the keyboard and another press on back button opens Homescreen/After hiding the keyboard with back button, pressing on home button opens home screen)
3. Swipe left to open App list > Click on Search > Keyboard is summoned > Press the home button ( it only hides the keyboard and does not open the Home Screen)
4. Swipe left to open App list > Click on Search > Keyboard is summoned > Swipe right to go to Home > On Home screen the keyboard remains summoned > Home button does not hide the keyboard (only back button hides the keyboard here)

### Expected behavior

1. Show all the options without extra swipe up on horizontal screen.
2. Hide the keyboard on Home screen.
3. Go to Home screen after hiding the keyboard.
4. Swipe left hides the keyboard to go to home screen.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by HeCodes2Much** [comment]
this should all be done but you can check after i do the next release.
