### ISSUE TITLE
[Bug Report] Cannot unlock a locked app

### ISSUE THREAD

**Issue by SerpentStrike** [DroidWorksStudio/EasyLauncher#88]
### Checklist

- [X] I will make sure to have the issue written in English with an English title.
- [X] I made sure that there are **no existing issues** - [open](https://github.com/DroidWorksStudio/mLauncher/issues) or [closed](https://github.com/DroidWorksStudio/mLauncher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I've verified that this issue hasn't been addressed in the [changelogs](https://github.com/DroidWorksStudio/mLauncher/blob/main/CHANGELOG.md).
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [ ] I optionally [donated](https://www.buymeacoffee.com/HeCodes2Much) to support the mLauncher mission.

### App version

0.1.6

### Android version

Android 11 Lineage OS

### How did you download the software?

F-Droid

### Bug description

Unable to access a locked app.
Once it's locked the app does not open nor can you unlock it from holding the app for the app menu.

### Steps to reproduce the bug

1. Tapped the locked app. No response.
2. Tap and hold the locked app for menu to tap unlock. No response. 

### Expected behavior

I expected for the launcher to prompt a swipe for pattern unlock since my device does not have fingerprint unlock (older device). Uninstalled the app and reinstalled fixed it however I should not have to go through that just to get the app working.

### Terms and Conditions

- [X] I have read all the rules above and filled in the requiered fields to the best of my ability.
- [X] I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project.

**Comment by Gitbot-Actions** [comment]
👋 Thanks for reporting!

  We will get back to you soon about this issue.

**Comment by HeCodes2Much** [comment]
oops sorry about that I forgot to also allow `DEVICE_CREDENTIAL` as one of the Authentication types but this will be fixed in the next release.

**Comment by SerpentStrike** [comment]
Legend! Looking forward to the next release, this has been a good launcher to use. Thanks for checking in the bug. Have a good one!
